#services:
 # - type: web
  #  name: inocencio
   # env: docker
    #buildCommand:  "docker-compose -f compose.yaml up --build"
 # envVars:
 # - key: DATABASE_URL
  #  fromDatabase:
   #   name: my-database
    #  property: connectionString

services:
  mytaier:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mytaier
      MYSQL_ROOT_PASSWORD: samsuroo
      MYSQL_PASSWORD: samsu
      MYSQL_USER: inoce
    ports:
      - "3307:3306"
    networks:
      - my-network
 

  spring-boot-container:
    build: .
    restart: always
    depends_on:
      - mytaier
    environment:
      SPRING_DATASOURCE_USERNAME: inoce
      SPRING_DATASOURCE_PASSWORD: samsu
      SPRING_DATASOURCE_URL: jdbc:mysql://mytaier:3306/mytaier?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    ports:
      - "8080:8080"   
    networks:
      - my-network
    volumes:
        - mysql_data:/var/lib/mysql


volumes:
  mysql_data:


networks:
  my-network:
  