services:
  - type: web
    name: inocencio
    env: docker
    buildCommand:  "docker-compose -f compose.yaml up --build"
 # envVars:
 # - key: DATABASE_URL
  #  fromDatabase:
   #   name: my-database
    #  property: connectionString

