services:
- type: web
  name: inocencio
  env: docker
  buildCommand: docker-compose build # docker-compose -f compose.yaml up --build
  startCommand: docker-compose up
 # envVars:
 # - key: DATABASE_URL
  #  fromDatabase:
   #   name: my-database
    #  property: connectionString