spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver #org.postgresql.Driver

    url: jdbc:${URL}
    #url: jdbc:mysql://mytaier:3306/mytaier?createDatabaseIfNotExist=true&serverTimezone=UTC&useServerPrepStmts=false&allowPublicKeyRetrieval=true
    #url:  jdbc:mysql://localhost:3306/publish?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSI=false
    username: ${USER}
    password: ${PASSWORD}


  jpa:
     hibernate:
       ddl-auto: update
       dialect: org.hibernate.dialect.MySQL8Dialect